version: "3.9"

services: 
    server: #nginx server https://hub.docker.com/_/nginx
        build:
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - '8000:80'
        volumes: # Use only in dev mode
            - ./src:/var/www/html # In the nginx.conf the root is given as root /var/www/html/public; so we need to bind the laravel apps src folder.  
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - php
            - mysql
    php: # Extended official php image with extensions
        build: 
            context: .
            dockerfile: dockerfiles/php.dockerfile
            args:
                - USER_ID=1000 # get using id -u
                - GROUP_ID=985 # get using id -g
        volumes: # Use only in development mode
            - ./src:/var/www/html:delegated # Can't use ro as php will write some data. Delegates batches the updates back to host improving performance
    mysql:
        image: mysql:5.7
        env_file:
            - ./env/mysql.env
    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
            args:
                - USER_ID=1000 # get using id -u
                - GROUP_ID=985 # get using id -g
        volumes:
            - ./src:/var/www/html
    artisan:
        build: 
            context: .
            dockerfile: dockerfiles/php.dockerfile
            args:
                - USER_ID=1000 # get using id -u
                - GROUP_ID=985 # get using id -g
        volumes:
            - ./src:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
    npm:
        image: node:14
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes: 
            - ./src:/var/www/html
    