version: "3.9"

services: 
    server: #nginx server https://hub.docker.com/_/nginx
        image: 'nginx:1.20.1-alpine'
        ports:
            - '8000:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    php: # Extended official php image with extensions
        build: 
            context: ./dockerfiles
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated # Can't use ro as php will write some data. Delegates batches the updates back to host improving performance
    mysql:
        image: mysql:5.7
        env_file:
            - ./env/mysql.env
    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
    # artisan:
    # npm:
    